### ISSUE TITLE
Heatmap legend is not correctly refreshed after applying filter

### ISSUE THREAD

**Issue by canasdiaz** [grimoirelab/kibiter#113] opened 2019-08-19 19:28 UTC
@GeorgLink found an error on the dashboard https://chaoss.biterg.io. The bug affects the legend of the heatmap, which is not correctly refreshed.

This is how you can reproduce it:
* click on https://chaoss.biterg.io/goto/b1475c26efeefbae1791dd583c8c7434
* using the dropdown menu on the left I select "Bitergia" and I click on the (-) filter on top to filter out Bitergia
* the legend is not updated (max should be around 1.4K)
![imagen](https://user-images.githubusercontent.com/326719/63293008-45fd0100-c2c7-11e9-8a35-d4314e4ee61e.png)
* if I hide the legend and click again to display it, the number is refreshed
![imagen](https://user-images.githubusercontent.com/326719/63293048-5e6d1b80-c2c7-11e9-8ee5-cae2833d5152.png)

**Comment by alpgarcia** [comment] 2019-08-20 08:28
Probably related to: https://github.com/elastic/kibana/issues/38818

**Comment by dlumbrer** [comment] 2019-08-26 10:03
I tested the behavior in a Kibiter 6.1.4 without our modifications and the result is the same as @sanacl showed. 


> Probably related to: [elastic#38818](https://github.com/elastic/kibana/issues/38818)

It seems that the issue is in Kibana

**Comment by sduenas** [comment] 2023-10-30 10:48
This error is fixed in OpenSearch 2.7.

**Closed as completed by sduenas** 2023-10-30 10:48 UTC
